# Generated by Django 2.2 on 2020-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201216_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by_current_user',
            field=models.BooleanField(default=False),
        ),
    ]
